#! /bin/bash

port=$1

if [ -z "$port" ]; then
	echo Need to specify port number
	exit 1
fi

FILES=($(ls bhtc | grep "\.py"))

mkdir bhtc$port
for file in "${FILES[@]}"; do
 	echo Syncing $file
	ln bhtc/$file bhtc$port/$file
done

echo Synced new bhtc folder for port $port
